version: '3.8'
services:
  beysik-ui:
    build:
      context: ./services/Beysik-UI
    ports:
      - "8001:8001"

  beysik-cartservice:
    build:
      context: ./services/Beysik-CartService
    ports:
      - "5001:5001"

  beysik-pcservice:
    build:
      context: ./services/Beysik-PCService
    ports:
      - "5002:5002"

  beysik-orderservice:
    build:
      context: ./services/Beysik-OrderService
    ports:
      - "5003:5003"

  rabbitmq:
    image: rabbitmq:4-management
    container_name: beysik-rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mongodb:
    image: mongo:latest
    container_name: beysik-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: ProductCatalog
      MONGO_INITDB_COLLECTION: Products
    volumes:
      - mongodb_data:/data/db

  yarp-gateway:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: yarp-gateway
    ports:
      - "8000:80"
    volumes:
      - ./services/Beysik-YARP/appsettings.json:/app/appsettings.json
    working_dir: /app
    entrypoint: ["dotnet", "Yarp.ReverseProxy.dll"]
    depends_on:
      - beysik-cartservice
      - beysik-pcservice
      - beysik-orderservice

  node-alpine-dev:
    image: docker.io/library/node:18-alpine
    container_name: node-alpine-dev
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: ["tail", "-f", "/dev/null"]

  dotnet-dev:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: dotnet-dev
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true

  node-dev:
    image: docker.io/library/node:18
    container_name: node-dev
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: ["tail", "-f", "/dev/null"]

volumes:
  rabbitmq_data:
    driver: local
  mongodb_data:
    driver: local
