version: '3.8'
services:
  Beysik-UI:
    build:
      context: ./services/Beysik-UI
    ports:
      - "8001:8001"

  Beysik-CartService:
    build:
      context: ./services/Beysik-CartService/Beysik-CartService/Beysik-CartService
    ports:
      - "5001:5001"

  Beysik-PCService:
    build:
      context: ./services/Beysik-PCService/Beysik-PCService/Beysik-PCService
    ports:
      - "5002:5002"

  Beysik-OrderService:
    build:
      context: ./services/Beysik-OrderService/Beysik-OrderService/Beysik-OrderService
    ports:
      - "5003:5003"

  rabbitmq:
    image: rabbitmq:4-management
    container_name: beysik-rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mongodb:
    image: mongo:latest
    container_name: beysik-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: ProductCatalog
      MONGO_INITDB_COLLECTION: Products
    volumes:
      - mongodb_data:/data/db

  yarp-gateway:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: yarp-gateway
    ports:
      - "8000:80"
    volumes:
      - ./services/Beysi-YARP/appsettings.json:/app/appsettings.json
    working_dir: /app
    entrypoint: ["dotnet", "Yarp.ReverseProxy.dll"]
    depends_on:
      - Beysik-UI
      - Beysik-CartService
      - Beysik-PCService
      - Beysik-OrderService
